// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: first.sql

package db

import (
	"context"
)

const create = `-- name: Create :exec

INSERT INTO products(id, name, price, description)
VALUES ($1, $2, $3, $4)
`

type CreateParams struct {
	ID          string
	Name        string
	Price       int32
	Description string
}

// Я использую pgx, в котором если не найдена строка
// при запросе одной строки, то возвращается ошибка;
// а если запрашивается несколько строк и не возвращается
// ни одной, то ошибки нет - будет пустой срез.
func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Description,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE
FROM products
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT name, price, description
FROM products
WHERE id = $1
`

type GetRow struct {
	Name        string
	Price       int32
	Description string
}

func (q *Queries) Get(ctx context.Context, id string) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(&i.Name, &i.Price, &i.Description)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT id, name, price
FROM products
`

type GetAllRow struct {
	ID    string
	Name  string
	Price int32
}

func (q *Queries) GetAll(ctx context.Context) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderedOffsetGetAll = `-- name: OrderedOffsetGetAll :many
SELECT id, name, price
FROM products
ORDER BY $1
LIMIT $2
OFFSET $3
`

type OrderedOffsetGetAllParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type OrderedOffsetGetAllRow struct {
	ID    string
	Name  string
	Price int32
}

func (q *Queries) OrderedOffsetGetAll(ctx context.Context, arg OrderedOffsetGetAllParams) ([]OrderedOffsetGetAllRow, error) {
	rows, err := q.db.Query(ctx, orderedOffsetGetAll, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderedOffsetGetAllRow
	for rows.Next() {
		var i OrderedOffsetGetAllRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec

UPDATE products
SET name = $2, price = $3, description = $4
WHERE id = $1
`

type UpdateParams struct {
	ID          string
	Name        string
	Price       int32
	Description string
}

// тут сначала будет Гет, потом из переданных в функцию
// аргументов выбираются ненулевые и заменяются в структуре из Гет
// и отправляются в БД
func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Description,
	)
	return err
}
