// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          string
	UserID      string
	Name        string
	Description string
	Price       int32
	CreatedAt   pgtype.Timestamptz
}
