// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO product(
    id,
    user_id,
    name,
    description,
    price
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, price, created_at
`

type CreateParams struct {
	ID          string
	UserID      string
	Name        string
	Description string
	Price       int32
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Product, error) {
	row := q.db.QueryRow(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE 
FROM product
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const deleteByUser = `-- name: DeleteByUser :exec
DELETE
FROM product
WHERE user_id = $1
`

func (q *Queries) DeleteByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteByUser, userID)
	return err
}

const getAll = `-- name: GetAll :many


SELECT id, user_id, name, description, price, created_at
FROM product
`

// imname: LimitImageNumber :one
// INSERT INTO product_image(product_id, max_count)
// VALUES ($1, $2)
// RETURNING *;
// imname: GetOne :one
// SELECT p.id, p.user_id, p.name, p.description, p.price, p.created_at, pi.max_count
// FROM product AS p INNER JOIN product_image AS pi ON p.id = pi.product_id
// WHERE p.id = $1;
func (q *Queries) GetAll(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatest = `-- name: GetLatest :many
SELECT id, user_id, name, description, price, created_at
FROM product
ORDER BY created_at DESC
LIMIT 10
`

func (q *Queries) GetLatest(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
